//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPro.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.foods = new HashSet<food>();
            this.Sceneries = new HashSet<Scenery>();
            this.Texts = new HashSet<Text>();
            this.TopBanners = new HashSet<TopBanner>();
        }
    
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string CoverImg { get; set; }
        public Nullable<int> IsDele { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ImgUrl { get; set; }
    
        public virtual ICollection<food> foods { get; set; }
        public virtual ICollection<Scenery> Sceneries { get; set; }
        public virtual ICollection<Text> Texts { get; set; }
        public virtual ICollection<TopBanner> TopBanners { get; set; }
    }
}
